package com.beckytech.english1000commonphrases.contents;

public class CategoryContent {
    public String[] categories = {
            "ask",
            "gived",
            "syno",
            "syimiss",
            "hotel",
            "sfexample",
            "clssroom",
            "hello",
            "shopping",
            "luck",
            "job",
            "agree",
            "sorry",
            "night",
            "love",
            "because",
            "idknow",
            "acceptapologies",
            "asksomeone",
            "hungry",
            "morning",
            "makingapologies",
            "accapology",
            "sayno",
            "goodbye",
            "sayyes",
            "birthday",
            "howareyou",
            "likeit",
            "omygod",
            "tired",
            "sayforeexample",
            "s_greeting",
            "g_greeting",
            "t_greeting",
            "lt_greeting",
            "welcome",
            "surprise",
            "greeted",
            "journey_or_vacation",
            "health_and_happines",
            "positive",
            "neutral",
            "negative",
            "explain",
            "drink coffee",

            "introducing",
            "just been introduced",
            "have been introduced",
            "ask how someone is",
            "ask how things",

            "end of conversation",
            "ending a telephone",
            "a conversation abruptly",

            "simple good bye",
            "leave of someone",
            "leaving a place",
            "leaving on a journey",
            "plans to keep in touch",

            "simple agreement",
            "state your concurrence",
            "express acceptance",
            "you understand",
            "making sure",

            "simple disagreement",
            "categorical disagreement",
            "strong disagreement",
            "disagreement with a proposition",
            "expressing rejection",
            "expressing refusal",
            "stating someone is wrong",
            "arguing about the facts",

            "Pardon me",
            "Look here",
            "Look at this",
            "i hear you",

            "informal conversation",
            "someone to talk",
            "point of the matter",
            "getting to the point",
            "conversational phrases",
            "speak plainly",
            "digressions in a conversation",
            "what you have said",
            "someone is being repetitious",
            "agreeing with speaker",
            "answers to",

            "expressing friendship",
            "uniqueness of someone",
            "personal similarities",
            "bar or cafe",
            "someone to dance",
            "opposite sex",
            "ask for date",
            "someone down",
            "to an end",

            "support for someone",
            "help to someone",
            "trust in someone",
            "encouragement",
            "try something",
            "stalling and do something",
            "someone efforts",
            "someone to wait",
            "patient and take slowly",
            "prudent cliches",
            "life is too busy",
            "lent something to",
            "a secret",
            "keeping a secret",
            "keep a secret",
            "forgetfulness",
            "you are in trouble",
            "someone in trouble",
            "out of money",
            "someone in debt",
            "stress or anxiety",
            "doing to much",
            "anxious and under stress",
            "offended informal",
            "not to be excited",
            "someone to relax",
            "less aggressive",
            "cold and unfeeling",
            "say to a smoker",
            "non smoker compliant",
            "smoker might ask",

            "ask",
            "ask",
            "ask",
            "ask",
            "ask",
            "ask",
            "ask",
            "ask",
            "ask",
            "ask",
            "ask",
            "ask",
            "ask",
            "ask",
            "ask",
            "ask",
            "ask",
            "ask",

            "gived",
            "gived",
            "gived",
            "gived",
            "gived",
            "gived",
            "gived",
            "gived",
            "gived",
            "gived",
            "gived",
            "gived",
            "gived",
            "gived",
            "gived",
            "gived",
            "gived",

            "syno",
            "syno",
            "syno",
            "syno",
            "syno",
            "syno",
            "syno",
            "syno",
            "syno",
            "syno",
            "syno",
            "syno",
            "syno",
            "syno",

            "syimiss",
            "syimiss",
            "syimiss",
            "syimiss",
            "syimiss",
            "syimiss",
            "syimiss",
            "syimiss",
            "syimiss",
            "syimiss",
            "syimiss",
            "syimiss",
            "syimiss",
            "syimiss",
            "syimiss",

            "hotel",
            "hotel",
            "hotel",
            "hotel",
            "hotel",
            "hotel",
            "hotel",
            "hotel",
            "hotel",
            "hotel",
            "hotel",
            "hotel",
            "hotel",
            "hotel",
            "hotel",

            "sfexample",
            "sfexample",
            "sfexample",
            "sfexample",
            "sfexample",
            "sfexample",
            "sfexample",
            "sfexample",
            "sfexample",
            "sfexample",
            "sfexample",
            "sfexample",
            "sfexample",
            "sfexample",
            "sfexample",
            "sfexample",
            "sfexample",
            "sfexample",
            "sfexample",
            "sfexample",
            "sfexample",
            "sfexample",
            "sfexample",
            "sfexample",

            "clssroom",
            "clssroom",
            "clssroom",
            "clssroom",
            "clssroom",
            "clssroom",
            "clssroom",
            "clssroom",
            "clssroom",
            "clssroom",
            "clssroom",
            "clssroom",
            "clssroom",
            "clssroom",
            "clssroom",
            "clssroom",
            "clssroom",
            "clssroom",
            "clssroom",
            "clssroom",
            "clssroom",
            "clssroom",
            "clssroom",
            "clssroom",
            "clssroom",
            "clssroom",
            "clssroom",
            "clssroom",
            "clssroom",

            "hello",
            "hello",
            "hello",
            "hello",
            "hello",
            "hello",
            "hello",
            "hello",
            "hello",
            "hello",
            "hello",
            "hello",
            "hello",
            "hello",
            "hello",
            "hello",
            "hello",
            "hello",
            "hello",

            "shopping",
            "shopping",
            "shopping",
            "shopping",
            "shopping",
            "shopping",
            "shopping",
            "shopping",
            "shopping",
            "shopping",
            "shopping",
            "shopping",
            "shopping",
            "shopping",
            "shopping",
            "shopping",

            "luck",
            "luck",
            "luck",
            "luck",
            "luck",
            "luck",
            "luck",
            "luck",
            "luck",
            "luck",
            "luck",
            "luck",
            "luck",
            "luck",
            "luck",

            "job",
            "job",
            "job",
            "job",
            "job",
            "job",
            "job",
            "job",
            "job",
            "job",
            "job",
            "job",
            "job",
            "job",
            "job",
            "job",
            "job",
            "job",

            "agree",
            "agree",
            "agree",
            "agree",
            "agree",
            "agree",
            "agree",
            "agree",
            "agree",
            "agree",
            "agree",
            "agree",
            "agree",
            "agree",
            "agree",
            "agree",

            "sorry",
            "sorry",
            "sorry",
            "sorry",
            "sorry",
            "sorry",
            "sorry",
            "sorry",
            "sorry",
            "sorry",
            "sorry",
            "sorry",
            "sorry",
            "sorry",
            "sorry",
            "sorry",

            "night",
            "night",
            "night",
            "night",
            "night",
            "night",
            "night",
            "night",
            "night",
            "night",
            "night",
            "night",
            "night",

            "love",
            "love",
            "love",
            "love",
            "love",
            "love",
            "love",
            "love",
            "love",
            "love",
            "love",
            "love",
            "love",
            "love",
            "love",
            "love",
            "love",
            "love",
            "love",
            "love",
            "love",
            "love",

            "because",
            "because",
            "because",
            "because",
            "because",
            "because",
            "because",
            "because",
            "because",
            "because",
            "because",
            "because",
            "because",
            "because",
            "because",
            "because",
            "because",
            "because",
            "because",
            "because",

            "idknow",
            "idknow",
            "idknow",
            "idknow",
            "idknow",
            "idknow",
            "idknow",
            "idknow",
            "idknow",
            "idknow",
            "idknow",
            "idknow",
            "idknow",
            "idknow",
            "idknow",
            "idknow",

            "acceptapologies",
            "acceptapologies",
            "acceptapologies",
            "acceptapologies",
            "acceptapologies",
            "acceptapologies",
            "acceptapologies",
            "acceptapologies",
            "acceptapologies",
            "acceptapologies",
            "acceptapologies",
            "acceptapologies",
            "acceptapologies",
            "acceptapologies",
            "acceptapologies",
            "acceptapologies",

            "asksomeone",
            "asksomeone",
            "asksomeone",
            "asksomeone",
            "asksomeone",
            "asksomeone",
            "asksomeone",
            "asksomeone",
            "asksomeone",

            "hungry",
            "hungry",
            "hungry",
            "hungry",
            "hungry",
            "hungry",
            "hungry",
            "hungry",
            "hungry",
            "hungry",
            "hungry",
            "hungry",
            "hungry",
            "hungry",
            "hungry",
            "hungry",

            "morning",
            "morning",
            "morning",
            "morning",
            "morning",
            "morning",
            "morning",
            "morning",

            "makingapologies",
            "makingapologies",
            "makingapologies",
            "makingapologies",
            "makingapologies",
            "makingapologies",
            "makingapologies",
            "makingapologies",
            "makingapologies",
            "makingapologies",
            "makingapologies",
            "makingapologies",
            "makingapologies",
            "makingapologies",
            "makingapologies",
            "makingapologies",
            "makingapologies",

            "accapology",
            "accapology",
            "accapology",
            "accapology",
            "accapology",
            "accapology",
            "accapology",
            "accapology",
            "accapology",
            "accapology",
            "accapology",
            "accapology",
            "accapology",
            "accapology",
            "accapology",
            "accapology",
            "accapology",

            "sayno",
            "sayno",
            "sayno",
            "sayno",
            "sayno",
            "sayno",
            "sayno",
            "sayno",
            "sayno",
            "sayno",
            "sayno",
            "sayno",
            "sayno",
            "sayno",
            "sayno",
            "sayno",
            "sayno",
            "sayno",
            "sayno",
            "sayno",
            "sayno",
            "sayno",
            "sayno",
            "sayno",
            "sayno",
            "sayno",
            "sayno",
            "sayno",
            "sayno",

            "goodbye",
            "goodbye",
            "goodbye",
            "goodbye",
            "goodbye",
            "goodbye",
            "goodbye",
            "goodbye",
            "goodbye",
            "goodbye",
            "goodbye",
            "goodbye",
            "goodbye",
            "goodbye",
            "goodbye",
            "goodbye",
            "goodbye",

            "sayyes",
            "sayyes",
            "sayyes",
            "sayyes",
            "sayyes",
            "sayyes",
            "sayyes",
            "sayyes",
            "sayyes",
            "sayyes",
            "sayyes",
            "sayyes",
            "sayyes",
            "sayyes",
            "sayyes",
            "sayyes",
            "sayyes",
            "sayyes",

            "birthday",
            "birthday",
            "birthday",
            "birthday",
            "birthday",
            "birthday",
            "birthday",
            "birthday",
            "birthday",
            "birthday",
            "birthday",
            "birthday",
            "birthday",
            "birthday",
            "birthday",

            "howareyou",
            "howareyou",
            "howareyou",
            "howareyou",
            "howareyou",
            "howareyou",
            "howareyou",
            "howareyou",
            "howareyou",
            "howareyou",
            "howareyou",
            "howareyou",

            "likeit",
            "likeit",
            "likeit",
            "likeit",
            "likeit",
            "likeit",
            "likeit",
            "likeit",
            "likeit",
            "likeit",
            "likeit",
            "likeit",
            "likeit",
            "likeit",
            "likeit",
            "likeit",

            "omygod",
            "omygod",
            "omygod",
            "omygod",
            "omygod",
            "omygod",
            "omygod",
            "omygod",
            "omygod",
            "omygod",
            "omygod",
            "omygod",
            "omygod",

            "tired",
            "tired",
            "tired",
            "tired",
            "tired",
            "tired",
            "tired",
            "tired",
            "tired",
            "tired",
            "tired",
            "tired",
            "tired",
            "tired",
            "tired",
            "tired",
            "tired",

            "sayforeexample",
            "sayforeexample",
            "sayforeexample",
            "sayforeexample",
            "sayforeexample",
            "sayforeexample",
            "sayforeexample",
            "sayforeexample",
            "sayforeexample",
            "sayforeexample",
            "sayforeexample",
            "sayforeexample",
            "sayforeexample",
            "sayforeexample",
            "sayforeexample",
            "sayforeexample",
            "sayforeexample",
            "sayforeexample",
            "sayforeexample",
            "sayforeexample",
            "sayforeexample",
            "sayforeexample",
            "sayforeexample",

            "s_greeting",
            "s_greeting",
            "s_greeting",
            "s_greeting",
            "s_greeting",

            "g_greeting",
            "g_greeting",
            "g_greeting",
            "g_greeting",
            "g_greeting",
            "g_greeting",
            "g_greeting",
            "g_greeting",
            "g_greeting",
            "g_greeting",
            "g_greeting",
            "g_greeting",
            "g_greeting",

            "t_greeting",
            "t_greeting",
            "t_greeting",
            "t_greeting",
            "t_greeting",
            "t_greeting",
            "t_greeting",

            "lt_greeting",
            "lt_greeting",
            "lt_greeting",
            "lt_greeting",

            "welcome",
            "welcome",
            "welcome",
            "welcome",

            "surprise",
            "surprise",
            "surprise",
            "surprise",
            "surprise",
            "surprise",
            "surprise",
            "surprise",
            "surprise",
            "surprise",
            "surprise",
            "surprise",
            "surprise",
            "surprise",

            "greeted",
            "greeted",
            "greeted",
            "greeted",
            "greeted",

            "journey_or_vacation",
            "journey_or_vacation",
            "journey_or_vacation",
            "journey_or_vacation",
            "journey_or_vacation",
            "journey_or_vacation",
            "journey_or_vacation",
            "journey_or_vacation",
            "journey_or_vacation",
            "journey_or_vacation",
            "journey_or_vacation",
            "journey_or_vacation",
            "journey_or_vacation",

            "health_and_happines",
            "health_and_happines",
            "health_and_happines",
            "health_and_happines",
            "health_and_happines",
            "health_and_happines",
            "health_and_happines",
            "health_and_happines",
            "health_and_happines",
            "health_and_happines",
            "health_and_happines",
            "health_and_happines",

            "positive",
            "positive",
            "positive",
            "positive",
            "positive",

            "neutral",
            "neutral",
            "neutral",
            "neutral",
            "neutral",
            "neutral",
            "neutral",
            "neutral",
            "neutral",
            "neutral",

            "negative",
            "negative",
            "negative",
            "negative",
            "negative",
            "negative",
            "negative",
            "negative",
            "negative",
            "negative",
            "negative",
            "negative",
            "negative",
            "negative",
            "negative",
            "negative",
            "negative",
            "negative",
            "negative",
            "negative",
            "negative",
            "negative",

            "explain",
            "explain",
            "explain",
            "explain",
            "explain",
            "explain",
            "explain",
            "explain",
            "explain",
            "explain",
            "explain",

            "drink coffee",
            "drink coffee",
            "drink coffee",
            "drink coffee",
            "drink coffee",

            "introducing",
            "introducing",
            "introducing",
            "introducing",
            "introducing",
            "introducing",
            "introducing",
            "introducing",
            "introducing",
            "introducing",
            "introducing",
            "introducing",

            "just been introduced",
            "just been introduced",
            "just been introduced",
            "just been introduced",
            "just been introduced",
            "just been introduced",
            "just been introduced",
            "just been introduced",
            "just been introduced",
            "just been introduced",
            "just been introduced",
            "just been introduced",

            "have been introduced",
            "have been introduced",
            "have been introduced",
            "have been introduced",
            "have been introduced",
            "have been introduced",
            "have been introduced",
            "have been introduced",

            "ask how someone is",
            "ask how someone is",
            "ask how someone is",
            "ask how someone is",
            "ask how someone is",
            "ask how someone is",
            "ask how someone is",
            "ask how someone is",
            "ask how someone is",
            "ask how someone is",
            "ask how someone is",

            "ask how things",
            "ask how things",
            "ask how things",
            "ask how things",
            "ask how things",
            "ask how things",
            "ask how things",
            "ask how things",
            "ask how things",
            "ask how things",
            "ask how things",
            "ask how things",
            "ask how things",
            "ask how things",
            "ask how things",
            "ask how things",

            "end of conversation",
            "end of conversation",
            "end of conversation",
            "end of conversation",
            "end of conversation",
            "end of conversation",
            "end of conversation",

            "ending a telephone",
            "ending a telephone",
            "ending a telephone",
            "ending a telephone",
            "ending a telephone",
            "ending a telephone",
            "ending a telephone",
            "ending a telephone",

            "a conversation abruptly",
            "a conversation abruptly",
            "a conversation abruptly",
            "a conversation abruptly",
            "a conversation abruptly",
            "a conversation abruptly",
            "a conversation abruptly",

            "simple good bye",
            "simple good bye",
            "simple good bye",
            "simple good bye",
            "simple good bye",
            "simple good bye",
            "simple good bye",
            "simple good bye",
            "simple good bye",
            "simple good bye",
            "simple good bye",
            "simple good bye",
            "simple good bye",
            "simple good bye",
            "simple good bye",
            "simple good bye",
            "simple good bye",
            "simple good bye",
            "simple good bye",
            "simple good bye",
            "simple good bye",
            "simple good bye",
            "simple good bye",
            "simple good bye",
            "simple good bye",
            "simple good bye",
            "simple good bye",
            "simple good bye",
            "simple good bye",
            "simple good bye",
            "simple good bye",
            "simple good bye",
            "simple good bye",
            "simple good bye",
            "simple good bye",
            "simple good bye",
            "simple good bye",
            "simple good bye",
            "simple good bye",
            "simple good bye",

            "leave of someone",
            "leave of someone",
            "leave of someone",
            "leave of someone",
            "leave of someone",
            "leave of someone",
            "leave of someone",
            "leave of someone",
            "leave of someone",

            "leaving a place",
            "leaving a place",
            "leaving a place",
            "leaving a place",
            "leaving a place",
            "leaving a place",
            "leaving a place",
            "leaving a place",
            "leaving a place",
            "leaving a place",
            "leaving a place",
            "leaving a place",
            "leaving a place",
            "leaving a place",
            "leaving a place",
            "leaving a place",
            "leaving a place",
            "leaving a place",
            "leaving a place",
            "leaving a place",
            "leaving a place",

            "leaving on a journey",
            "leaving on a journey",
            "leaving on a journey",
            "leaving on a journey",
            "leaving on a journey",
            "leaving on a journey",
            "leaving on a journey",
            "leaving on a journey",
            "leaving on a journey",
            "leaving on a journey",

            "plans to keep in touch",
            "plans to keep in touch",
            "plans to keep in touch",
            "plans to keep in touch",
            "plans to keep in touch",
            "plans to keep in touch",
            "plans to keep in touch",
            "plans to keep in touch",
            "plans to keep in touch",
            "plans to keep in touch",

            "simple agreement",
            "simple agreement",
            "simple agreement",
            "simple agreement",
            "simple agreement",
            "simple agreement",
            "simple agreement",
            "simple agreement",
            "simple agreement",
            "simple agreement",
            "simple agreement",
            "simple agreement",
            "simple agreement",
            "simple agreement",
            "simple agreement",

            "state your concurrence",
            "state your concurrence",
            "state your concurrence",
            "state your concurrence",
            "state your concurrence",
            "state your concurrence",
            "state your concurrence",
            "state your concurrence",
            "state your concurrence",
            "state your concurrence",
            "state your concurrence",
            "state your concurrence",
            "state your concurrence",
            "state your concurrence",
            "state your concurrence",
            "state your concurrence",
            "state your concurrence",
            "state your concurrence",
            "state your concurrence",
            "state your concurrence",

            "express acceptance",
            "express acceptance",
            "express acceptance",
            "express acceptance",
            "express acceptance",
            "express acceptance",
            "express acceptance",
            "express acceptance",
            "express acceptance",
            "express acceptance",
            "express acceptance",
            "express acceptance",
            "express acceptance",
            "express acceptance",
            "express acceptance",
            "express acceptance",
            "express acceptance",
            "express acceptance",
            "express acceptance",
            "express acceptance",
            "express acceptance",
            "express acceptance",
            "express acceptance",
            "express acceptance",
            "express acceptance",
            "express acceptance",
            "express acceptance",
            "express acceptance",
            "express acceptance",
            "express acceptance",
            "express acceptance",
            "express acceptance",
            "express acceptance",
            "express acceptance",
            "express acceptance",
            "express acceptance",
            "express acceptance",
            "express acceptance",
            "express acceptance",
            "express acceptance",
            "express acceptance",
            "express acceptance",
            "express acceptance",
            "express acceptance",
            "express acceptance",
            "express acceptance",
            "express acceptance",

            "you understand",
            "you understand",
            "you understand",
            "you understand",
            "you understand",
            "you understand",
            "you understand",
            "you understand",
            "you understand",
            "you understand",
            "you understand",
            "you understand",
            "you understand",
            "you understand",
            "you understand",
            "you understand",
            "you understand",
            "you understand",
            "you understand",
            "you understand",
            "you understand",
            "you understand",
            "you understand",
            "you understand",
            "you understand",
            "you understand",

            "making sure",
            "making sure",
            "making sure",
            "making sure",
            "making sure",
            "making sure",
            "making sure",
            "making sure",
            "making sure",
            "making sure",
            "making sure",
            "making sure",
            "making sure",
            "making sure",
            "making sure",
            "making sure",
            "making sure",
            "making sure",
            "making sure",
            "making sure",
            "making sure",
            "making sure",
            "making sure",
            "making sure",
            "making sure",
            "making sure",
            "making sure",
            "making sure",
            "making sure",
            "making sure",

            "simple disagreement",
            "simple disagreement",
            "simple disagreement",
            "simple disagreement",
            "simple disagreement",
            "simple disagreement",
            "simple disagreement",

            "categorical disagreement",
            "categorical disagreement",
            "categorical disagreement",
            "categorical disagreement",
            "categorical disagreement",
            "categorical disagreement",
            "categorical disagreement",
            "categorical disagreement",
            "categorical disagreement",
            "categorical disagreement",
            "categorical disagreement",

            "strong disagreement",
            "strong disagreement",
            "strong disagreement",
            "strong disagreement",
            "strong disagreement",
            "strong disagreement",
            "strong disagreement",
            "strong disagreement",
            "strong disagreement",
            "strong disagreement",
            "strong disagreement",
            "strong disagreement",
            "strong disagreement",
            "strong disagreement",
            "strong disagreement",

            "disagreement with a proposition",
            "disagreement with a proposition",
            "disagreement with a proposition",
            "disagreement with a proposition",

            "expressing rejection",
            "expressing rejection",
            "expressing rejection",
            "expressing rejection",
            "expressing rejection",
            "expressing rejection",
            "expressing rejection",
            "expressing rejection",
            "expressing rejection",
            "expressing rejection",
            "expressing rejection",
            "expressing rejection",
            "expressing rejection",
            "expressing rejection",
            "expressing rejection",
            "expressing rejection",

            "expressing refusal",
            "expressing refusal",
            "expressing refusal",
            "expressing refusal",
            "expressing refusal",
            "expressing refusal",
            "expressing refusal",
            "expressing refusal",
            "expressing refusal",
            "expressing refusal",
            "expressing refusal",
            "expressing refusal",
            "expressing refusal",
            "expressing refusal",
            "expressing refusal",
            "expressing refusal",
            "expressing refusal",
            "expressing refusal",
            "expressing refusal",
            "expressing refusal",
            "expressing refusal",
            "expressing refusal",
            "expressing refusal",
            "expressing refusal",
            "expressing refusal",
            "expressing refusal",
            "expressing refusal",
            "expressing refusal",
            "expressing refusal",
            "expressing refusal",
            "expressing refusal",
            "expressing refusal",
            "expressing refusal",
            "expressing refusal",
            "expressing refusal",
            "expressing refusal",
            "expressing refusal",
            "expressing refusal",
            "expressing refusal",

            "stating someone is wrong",
            "stating someone is wrong",
            "stating someone is wrong",
            "stating someone is wrong",
            "stating someone is wrong",
            "stating someone is wrong",
            "stating someone is wrong",

            "arguing about the facts",
            "arguing about the facts",
            "arguing about the facts",
            "arguing about the facts",
            "arguing about the facts",
            "arguing about the facts",
            "arguing about the facts",
            "arguing about the facts",
            "arguing about the facts",

            "Pardon me",
            "Pardon me",
            "Pardon me",
            "Pardon me",

            "Look here",
            "Look here",
            "Look here",
            "Look here",
            "Look here",
            "Look here",
            "Look here",
            "Look here",
            "Look here",
            "Look here",
            "Look here",
            "Look here",
            "Look here",
            "Look here",
            "Look here",

            "Look at this",
            "Look at this",
            "Look at this",
            "Look at this",
            "Look at this",
            "Look at this",
            "Look at this",
            "Look at this",
            "Look at this",
            "Look at this",
            "Look at this",
            "Look at this",
            "Look at this",

            "i hear you",
            "i hear you",
            "i hear you",
            "i hear you",

            "informal conversation",
            "informal conversation",
            "informal conversation",
            "informal conversation",
            "informal conversation",
            "informal conversation",
            "informal conversation",
            "informal conversation",
            "informal conversation",
            "informal conversation",
            "informal conversation",
            "informal conversation",
            "informal conversation",
            "informal conversation",

            "someone to talk",
            "someone to talk",
            "someone to talk",
            "someone to talk",
            "someone to talk",
            "someone to talk",

            "point of the matter",
            "point of the matter",
            "point of the matter",
            "point of the matter",
            "point of the matter",
            "point of the matter",
            "point of the matter",

            "getting to the point",
            "getting to the point",
            "getting to the point",
            "getting to the point",
            "getting to the point",
            "getting to the point",
            "getting to the point",
            "getting to the point",
            "getting to the point",
            "getting to the point",

            "conversational phrases",
            "conversational phrases",
            "conversational phrases",
            "conversational phrases",
            "conversational phrases",
            "conversational phrases",
            "conversational phrases",
            "conversational phrases",

            "speak plainly",
            "speak plainly",
            "speak plainly",
            "speak plainly",
            "speak plainly",
            "speak plainly",
            "speak plainly",
            "speak plainly",
            "speak plainly",
            "speak plainly",
            "speak plainly",
            "speak plainly",
            "speak plainly",
            "speak plainly",
            "speak plainly",

            "digressions in a conversation",
            "digressions in a conversation",
            "digressions in a conversation",
            "digressions in a conversation",
            "digressions in a conversation",
            "digressions in a conversation",
            "digressions in a conversation",
            "digressions in a conversation",
            "digressions in a conversation",
            "digressions in a conversation",
            "digressions in a conversation",
            "digressions in a conversation",
            "digressions in a conversation",
            "digressions in a conversation",
            "digressions in a conversation",
            "digressions in a conversation",
            "digressions in a conversation",
            "digressions in a conversation",
            "digressions in a conversation",
            "digressions in a conversation",

            "what you have said",
            "what you have said",
            "what you have said",
            "what you have said",
            "what you have said",
            "what you have said",
            "what you have said",
            "what you have said",
            "what you have said",
            "what you have said",

            "someone is being repetitious",
            "someone is being repetitious",
            "someone is being repetitious",
            "someone is being repetitious",
            "someone is being repetitious",
            "someone is being repetitious",
            "someone is being repetitious",

            "agreeing with speaker",
            "agreeing with speaker",
            "agreeing with speaker",
            "agreeing with speaker",
            "agreeing with speaker",
            "agreeing with speaker",
            "agreeing with speaker",

            "answers to",
            "answers to",
            "answers to",
            "answers to",
            "answers to",
            "answers to",
            "answers to",
            "answers to",
            "answers to",
            "answers to",
            "answers to",
            "answers to",
            "answers to",
            "answers to",
            "answers to",
            "answers to",

            "expressing friendship",
            "expressing friendship",
            "expressing friendship",
            "expressing friendship",
            "expressing friendship",
            "expressing friendship",
            "expressing friendship",
            "expressing friendship",
            "expressing friendship",
            "expressing friendship",
            "expressing friendship",

            "uniqueness of someone",
            "uniqueness of someone",
            "uniqueness of someone",
            "uniqueness of someone",
            "uniqueness of someone",

            "personal similarities",
            "personal similarities",
            "personal similarities",
            "personal similarities",
            "personal similarities",

            "bar or cafe",
            "bar or cafe",
            "bar or cafe",
            "bar or cafe",
            "bar or cafe",
            "bar or cafe",
            "bar or cafe",
            "bar or cafe",
            "bar or cafe",
            "bar or cafe",
            "bar or cafe",
            "bar or cafe",
            "bar or cafe",
            "bar or cafe",

            "someone to dance",
            "someone to dance",
            "someone to dance",
            "someone to dance",

            "opposite sex",
            "opposite sex",
            "opposite sex",
            "opposite sex",
            "opposite sex",
            "opposite sex",
            "opposite sex",
            "opposite sex",
            "opposite sex",
            "opposite sex",
            "opposite sex",
            "opposite sex",
            "opposite sex",
            "opposite sex",
            "opposite sex",
            "opposite sex",
            "opposite sex",
            "opposite sex",

            "ask for date",
            "ask for date",
            "ask for date",
            "ask for date",
            "ask for date",
            "ask for date",
            "ask for date",
            "ask for date",
            "ask for date",
            "ask for date",

            "someone down",
            "someone down",
            "someone down",
            "someone down",
            "someone down",
            "someone down",
            "someone down",
            "someone down",
            "someone down",
            "someone down",
            "someone down",
            "someone down",

            "to an end",
            "to an end",
            "to an end",
            "to an end",
            "to an end",
            "to an end",
            "to an end",
            "to an end",

            "support for someone",
            "support for someone",
            "support for someone",
            "support for someone",
            "support for someone",
            "support for someone",
            "support for someone",
            "support for someone",
            "support for someone",
            "support for someone",
            "support for someone",
            "support for someone",
            "support for someone",

            "help to someone",
            "help to someone",
            "help to someone",
            "help to someone",
            "help to someone",
            "help to someone",
            "help to someone",

            "trust in someone",
            "trust in someone",
            "trust in someone",
            "trust in someone",
            "trust in someone",
            "trust in someone",

            "encouragement",
            "encouragement",
            "encouragement",
            "encouragement",
            "encouragement",
            "encouragement",
            "encouragement",
            "encouragement",
            "encouragement",
            "encouragement",
            "encouragement",
            "encouragement",
            "encouragement",
            "encouragement",
            "encouragement",
            "encouragement",
            "encouragement",

            "try something",
            "try something",
            "try something",
            "try something",
            "try something",
            "try something",
            "try something",
            "try something",
            "try something",
            "try something",
            "try something",
            "try something",
            "try something",
            "try something",
            "try something",
            "try something",
            "try something",
            "try something",
            "try something",
            "try something",
            "try something",
            "try something",
            "try something",

            "stalling and do something",
            "stalling and do something",
            "stalling and do something",
            "stalling and do something",
            "stalling and do something",
            "stalling and do something",
            "stalling and do something",
            "stalling and do something",
            "stalling and do something",
            "stalling and do something",
            "stalling and do something",
            "stalling and do something",

            "someone efforts",
            "someone efforts",
            "someone efforts",
            "someone efforts",
            "someone efforts",
            "someone efforts",
            "someone efforts",
            "someone efforts",
            "someone efforts",

            "someone to wait",
            "someone to wait",
            "someone to wait",
            "someone to wait",
            "someone to wait",
            "someone to wait",
            "someone to wait",
            "someone to wait",
            "someone to wait",
            "someone to wait",
            "someone to wait",
            "someone to wait",
            "someone to wait",
            "someone to wait",
            "someone to wait",
            "someone to wait",
            "someone to wait",

            "patient and take slowly",
            "patient and take slowly",
            "patient and take slowly",
            "patient and take slowly",
            "patient and take slowly",
            "patient and take slowly",
            "patient and take slowly",
            "patient and take slowly",
            "patient and take slowly",
            "patient and take slowly",
            "patient and take slowly",
            "patient and take slowly",
            "patient and take slowly",
            "patient and take slowly",
            "patient and take slowly",
            "patient and take slowly",
            "patient and take slowly",
            "patient and take slowly",
            "patient and take slowly",
            "patient and take slowly",
            "patient and take slowly",
            "patient and take slowly",
            "patient and take slowly",
            "patient and take slowly",
            "patient and take slowly",
            "patient and take slowly",
            "patient and take slowly",
            "patient and take slowly",
            "patient and take slowly",
            "patient and take slowly",
            "patient and take slowly",

            "prudent cliches",
            "prudent cliches",
            "prudent cliches",
            "prudent cliches",
            "prudent cliches",
            "prudent cliches",
            "prudent cliches",
            "prudent cliches",
            "prudent cliches",

            "life is too busy",
            "life is too busy",
            "life is too busy",
            "life is too busy",
            "life is too busy",
            "life is too busy",
            "life is too busy",
            "life is too busy",
            "life is too busy",
            "life is too busy",
            "life is too busy",
            "life is too busy",

            "lent something to",
            "lent something to",
            "lent something to",
            "lent something to",
            "lent something to",
            "lent something to",
            "lent something to",
            "lent something to",
            "lent something to",

            "a secret",
            "a secret",
            "a secret",
            "a secret",
            "a secret",
            "a secret",
            "a secret",
            "a secret",
            "a secret",
            "a secret",
            "a secret",

            "keeping a secret",
            "keeping a secret",
            "keeping a secret",
            "keeping a secret",
            "keeping a secret",
            "keeping a secret",
            "keeping a secret",
            "keeping a secret",
            "keeping a secret",
            "keeping a secret",
            "keeping a secret",
            "keeping a secret",
            "keeping a secret",
            "keeping a secret",
            "keeping a secret",
            "keeping a secret",
            "keeping a secret",
            "keeping a secret",
            "keeping a secret",
            "keeping a secret",
            "keeping a secret",

            "keep a secret",
            "keep a secret",
            "keep a secret",
            "keep a secret",
            "keep a secret",

            "forgetfulness",
            "forgetfulness",
            "forgetfulness",
            "forgetfulness",
            "forgetfulness",
            "forgetfulness",
            "forgetfulness",
            "forgetfulness",
            "forgetfulness",
            "forgetfulness",
            "forgetfulness",
            "forgetfulness",
            "forgetfulness",
            "forgetfulness",
            "forgetfulness",
            "forgetfulness",
            "forgetfulness",
            "forgetfulness",

            "you are in trouble",
            "you are in trouble",
            "you are in trouble",
            "you are in trouble",
            "you are in trouble",
            "you are in trouble",
            "you are in trouble",
            "you are in trouble",
            "you are in trouble",
            "you are in trouble",
            "you are in trouble",
            "you are in trouble",
            "you are in trouble",

            "someone in trouble",
            "someone in trouble",
            "someone in trouble",
            "someone in trouble",
            "someone in trouble",
            "someone in trouble",
            "someone in trouble",
            "someone in trouble",
            "someone in trouble",
            "someone in trouble",
            "someone in trouble",
            "someone in trouble",
            "someone in trouble",
            "someone in trouble",
            "someone in trouble",
            "someone in trouble",

            "out of money",
            "out of money",
            "out of money",
            "out of money",
            "out of money",
            "out of money",
            "out of money",
            "out of money",
            "out of money",
            "out of money",
            "out of money",
            "out of money",
            "out of money",
            "out of money",
            "out of money",
            "out of money",
            "out of money",
            "out of money",

            "someone in debt",
            "someone in debt",
            "someone in debt",
            "someone in debt",
            "someone in debt",
            "someone in debt",

            "stress or anxiety",
            "stress or anxiety",
            "stress or anxiety",
            "stress or anxiety",
            "stress or anxiety",
            "stress or anxiety",
            "stress or anxiety",
            "stress or anxiety",
            "stress or anxiety",
            "stress or anxiety",
            "stress or anxiety",
            "stress or anxiety",
            "stress or anxiety",
            "stress or anxiety",
            "stress or anxiety",
            "stress or anxiety",
            "stress or anxiety",
            "stress or anxiety",
            "stress or anxiety",
            "stress or anxiety",

            "doing to much",
            "doing to much",

            "anxious and under stress",
            "anxious and under stress",
            "anxious and under stress",
            "anxious and under stress",
            "anxious and under stress",
            "anxious and under stress",
            "anxious and under stress",
            "anxious and under stress",
            "anxious and under stress",

            "offended informal",
            "offended informal",
            "offended informal",
            "offended informal",

            "not to be excited",
            "not to be excited",
            "not to be excited",
            "not to be excited",
            "not to be excited",
            "not to be excited",
            "not to be excited",
            "not to be excited",
            "not to be excited",
            "not to be excited",
            "not to be excited",
            "not to be excited",
            "not to be excited",
            "not to be excited",
            "not to be excited",
            "not to be excited",

            "someone to relax",
            "someone to relax",
            "someone to relax",
            "someone to relax",
            "someone to relax",
            "someone to relax",
            "someone to relax",
            "someone to relax",
            "someone to relax",
            "someone to relax",
            "someone to relax",
            "someone to relax",
            "someone to relax",
            "someone to relax",
            "someone to relax",
            "someone to relax",
            "someone to relax",
            "someone to relax",
            "someone to relax",
            "someone to relax",
            "someone to relax",

            "less aggressive",
            "less aggressive",
            "less aggressive",
            "less aggressive",
            "less aggressive",
            "less aggressive",

            "cold and unfeeling",
            "cold and unfeeling",
            "cold and unfeeling",
            "cold and unfeeling",
            "cold and unfeeling",
            "cold and unfeeling",
            "cold and unfeeling",
            "cold and unfeeling",
            "cold and unfeeling",
            "cold and unfeeling",
            "cold and unfeeling",
            "cold and unfeeling",
            "cold and unfeeling",
            "cold and unfeeling",

            "say to a smoker",
            "say to a smoker",
            "say to a smoker",
            "say to a smoker",
            "say to a smoker",
            "say to a smoker",
            "say to a smoker",
            "say to a smoker",
            "say to a smoker",
            "say to a smoker",
            "say to a smoker",

            "non smoker compliant",
            "non smoker compliant",
            "non smoker compliant",
            "non smoker compliant",
            "non smoker compliant",
            "non smoker compliant",

            "smoker might ask",
            "smoker might ask",
            "smoker might ask",
            "smoker might ask",
            "smoker might ask",
            "smoker might ask",
            "smoker might ask"
    };
}
