package com.beckytech.english1000commonphrases.contents;

public class SubTitleContent {
    public String[] subTitle = {
            "ask direction",
            "give direction",
            "say no in english",
            "say i miss you",
            "hotel",
            "say for example",
            "classroom",
            "say hello",
            "shopping",
            "say good luck",
            "say good job",
            "say I agree",
            "say i am sorry",
            "say good night",
            "say I love you",
            "say because",
            "say i don't know",
            "accept apologies",
            "repeat something",
            "say i am hungry",
            "say good morning",
            "making apologies",
            "accepting apologies",
            "say no",
            "say goodbye",
            "say yes",
            "Birthday",
            "how are you",
            "i don't like it",
            "oh my god",
            "i am tired",
            "say for example in other way",
            "greeting",
            "greeting",
            "greeting",
            "greeting",
            "welcome",
            "surprise",
            "greeted someone",
            "journey or vacation",
            "Small Talk",
            "Small Talk",
            "Small Talk",
            "Small Talk",
            "Small Talk",
            "Small Talk",

            "Introductions",
            "Introductions",
            "Introductions",
            "Introductions",
            "Introductions",

            "Ending a Conversation",
            "Ending a Conversation",
            "Ending a Conversation",

            "Goodbye",
            "Goodbye",
            "Goodbye",
            "Goodbye",
            "Goodbye",

            "agreeing",
            "agreeing",
            "agreeing",
            "agreeing",
            "agreeing",

            "disagreeing",
            "disagreeing",
            "disagreeing",
            "disagreeing",
            "disagreeing",
            "disagreeing",
            "disagreeing",
            "disagreeing",

            "focusing attention",
            "focusing attention",
            "focusing attention",
            "focusing attention",

            "launching the conversation",
            "launching the conversation",
            "launching the conversation",
            "launching the conversation",
            "launching the conversation",
            "launching the conversation",
            "launching the conversation",
            "launching the conversation",
            "launching the conversation",
            "launching the conversation",
            "launching the conversation",

            "making friends",
            "making friends",
            "making friends",
            "making friends",
            "making friends",
            "making friends",
            "making friends",
            "making friends",
            "making friends",

            "complex matters",
            "complex matters",
            "complex matters",
            "complex matters",
            "complex matters",
            "complex matters",
            "complex matters",
            "complex matters",
            "complex matters",
            "complex matters",
            "complex matters",
            "complex matters",
            "complex matters",
            "complex matters",
            "complex matters",
            "complex matters",
            "complex matters",
            "complex matters",
            "complex matters",
            "complex matters",
            "complex matters",
            "complex matters",
            "complex matters",
            "complex matters",
            "complex matters",
            "complex matters",
            "complex matters",
            "complex matters",
            "complex matters",
            "complex matters",
            "complex matters",

            "Disputes",
            "Disputes",
            "Disputes",
            "Disputes",
            "Disputes",
            "Disputes",
            "Disputes",

            "discussion and resolution",
            "discussion and resolution",
            "discussion and resolution",
            "discussion and resolution",
            "discussion and resolution",
            "discussion and resolution",
            "discussion and resolution",
            "discussion and resolution",
            "discussion and resolution",
            "discussion and resolution",
            "discussion and resolution",
            "discussion and resolution",
            "discussion and resolution",
            "discussion and resolution",
            "discussion and resolution",
            "discussion and resolution",
            "discussion and resolution",

            "POLITE ENCOUNTERS - Prefaces",
            "POLITE ENCOUNTERS - Prefaces",
            "POLITE ENCOUNTERS - Prefaces",
            "POLITE ENCOUNTERS - Prefaces",

            "Communication Barriers",
            "Communication Barriers",
            "Communication Barriers",
            "Communication Barriers",

            "Telling Time",
            "Telling Time",
            "Telling Time",
            "Telling Time",
            "Telling Time",
            "Telling Time",
            "Telling Time",
            "Telling Time",
            "Telling Time",
            "Telling Time",

            "General Pleasantries",
            "General Pleasantries",
            "General Pleasantries",
            "General Pleasantries",
            "General Pleasantries",
            "General Pleasantries",
            "General Pleasantries",
            "General Pleasantries",
            "General Pleasantries",

            "business pleasantries",
            "business pleasantries",

            "apologizing and taking responsibility",
            "apologizing and taking responsibility",
            "apologizing and taking responsibility",
            "apologizing and taking responsibility",
            "apologizing and taking responsibility",
            "apologizing and taking responsibility",
            "apologizing and taking responsibility",

            "forgiving",
            "forgiving",
            "forgiving",

            "showing gratitude",
            "showing gratitude",

            "Acknowledging thanks - formal",
            "Acknowledging thanks - informal",

            "special occasions",
            "special occasions",
            "special occasions",
            "special occasions",
            "special occasions",

            "Dealing with Unpleasantness",
            "Dealing with Unpleasantness",
            "Dealing with Unpleasantness",
            "Dealing with Unpleasantness",
            "Dealing with Unpleasantness",
            "Dealing with Unpleasantness",
            "Dealing with Unpleasantness",
            "Dealing with Unpleasantness",
            "Dealing with Unpleasantness",
            "Dealing with Unpleasantness",
            "Dealing with Unpleasantness",
            "Dealing with Unpleasantness",
            "Dealing with Unpleasantness",
            "Dealing with Unpleasantness",
            "Dealing with Unpleasantness",
            "Dealing with Unpleasantness",
            "Dealing with Unpleasantness",
            "Dealing with Unpleasantness",
            "Dealing with Unpleasantness",
            "Dealing with Unpleasantness",
            "Dealing with Unpleasantness",
            "Dealing with Unpleasantness",
            "Dealing with Unpleasantness",
            "Dealing with Unpleasantness",
            "Dealing with Unpleasantness",
            "Dealing with Unpleasantness",
            "Dealing with Unpleasantness",
            "Dealing with Unpleasantness",
            "Dealing with Unpleasantness",
            "Dealing with Unpleasantness",
            "Dealing with Unpleasantness",
            "Dealing with Unpleasantness",
            "Dealing with Unpleasantness",
            "Dealing with Unpleasantness",
            "Dealing with Unpleasantness",
            "Dealing with Unpleasantness",
            "Dealing with Unpleasantness",
            "Dealing with Unpleasantness",
            "Dealing with Unpleasantness",
            "Dealing with Unpleasantness",

            "visits",
            "visits",
            "visits",
            "visits",
            "visits",
            "visits",
            "visits",
            "visits",
            "visits",
            "visits",
            "visits",
            "visits",
            "visits",
            "visits",
            "visits",
            "visits",
            "visits",
            "visits",
            "visits",
            "visits",
            "visits",
            "visits",
            "visits",
            "visits",
            "visits",
            "visits",
            "visits",
            "visits",
            "visits",

            "Comments and Phrases",
            "Comments and Phrases",
            "Comments and Phrases",
            "Comments and Phrases",
            "Comments and Phrases",
            "Comments and Phrases",
            "Comments and Phrases",
            "Comments and Phrases",
            "Comments and Phrases",
            "Comments and Phrases",
            "Comments and Phrases",
            "Comments and Phrases",
            "Comments and Phrases",
            "Comments and Phrases",
            "Comments and Phrases",
            "Comments and Phrases",
            "Comments and Phrases",
            "Comments and Phrases",
            "Comments and Phrases",
            "Comments and Phrases",
            "Comments and Phrases",
            "Comments and Phrases",
            "Comments and Phrases",
            "Comments and Phrases",
            "Comments and Phrases",
            "Comments and Phrases",
            "Comments and Phrases",
            "Comments and Phrases",
            "Comments and Phrases",
            "Comments and Phrases",
            "Comments and Phrases",
            "Comments and Phrases",
            "Comments and Phrases",
            "Comments and Phrases",

            "Plans and Projects",
            "Plans and Projects",
            "Plans and Projects",
            "Plans and Projects",
            "Plans and Projects",
            "Plans and Projects",
            "Plans and Projects",

            "feelings",
            "feelings",
            "feelings",
            "feelings",
            "feelings",
            "feelings",
            "feelings",
            "feelings",
            "feelings",
            "feelings",
            "feelings",
            "feelings",
            "feelings",
            "feelings",
            "feelings",
            "feelings",
            "feelings",

            "Anxiety",
            "Anxiety",
            "Anxiety",
            "Anxiety",

            "The Senses",
            "The Senses",
            "The Senses",
            "The Senses",
            "The Senses",
            "The Senses",
            "The Senses",
            "The Senses",
            "The Senses",
            "The Senses",
            "The Senses",
            "The Senses",
            "The Senses",

            "Health and Appearance",
            "Health and Appearance",
            "Health and Appearance",
            "Health and Appearance",
            "Health and Appearance",

            "Sickness",
            "Sickness",
            "Sickness",
            "Sickness",
            "Sickness",
            "Sickness",
            "Sickness",
            "Sickness",
            "Sickness",
            "Sickness",
            "Sickness",
            "Sickness",
            "Sickness",
            "Sickness",
            "Sickness",
            "Sickness",
            "Sickness",

            "Home Life",
            "Home Life",
            "Home Life",
            "Home Life",
            "Home Life",
            "Home Life",
            "Home Life",
            "Home Life",
            "Home Life",
            "Home Life",
            "Home Life",
            "Home Life",
            "Home Life",
            "Home Life",
            "Home Life",
            "Home Life",
            "Home Life",
            "Home Life",
            "Home Life",
            "Home Life",
            "Home Life",
            "Home Life",
            "Home Life",

            "Education",
            "Education",
            "Education",
            "Education",
            "Education",
            "Education",
            "Education",
            "Education",

            "Children",
            "Children",
            "Children",
            "Children",
            "Children",
            "Children",
            "Children",
            "Children",
            "Children",
            "Children",
            "Children",

            "Restaurants",
            "Restaurants",
            "Restaurants",
            "Restaurants",
            "Restaurants",
            "Restaurants",
            "Restaurants",
            "Restaurants",
            "Restaurants",
            "Restaurants",
            "Restaurants",
            "Restaurants",
            "Restaurants",
            "Restaurants",
            "Restaurants",
            "Restaurants",
            "Restaurants",
            "Restaurants",
            "Restaurants",
            "Restaurants",
            "Restaurants",
            "Restaurants",
            "Restaurants",
            "Restaurants",
            "Restaurants",
            "Restaurants",
            "Restaurants",
            "Restaurants",
            "Restaurants",
            "Restaurants",

            "Bars",
            "Bars",
            "Bars",
            "Bars",
            "Bars",
            "Bars",
            "Bars",
            "Bars",
            "Bars",
            "Bars",
            "Bars",
            "Bars",
            "Bars",
            "Bars",
            "Bars",
            "Bars",

            "Home cooking",
            "Home cooking",
            "Home cooking",
            "Home cooking",
            "Home cooking",
            "Home cooking",
            "Home cooking",
            "Home cooking",
            "Home cooking",
            "Home cooking",
            "Home cooking",
            "Home cooking",

            "Stores and shops",
            "Stores and shops",
            "Stores and shops",
            "Stores and shops",
            "Stores and shops",
            "Stores and shops",
            "Stores and shops",
            "Stores and shops",
            "Stores and shops",
            "Stores and shops",
            "Stores and shops",
            "Stores and shops",
            "Stores and shops",
            "Stores and shops",
            "Stores and shops",
            "Stores and shops",
            "Stores and shops",
            "Stores and shops",

            "Answering the telephone",
            "Answering the telephone",
            "Answering the telephone",
            "Answering the telephone",
            "Answering the telephone",
            "Answering the telephone",
            "Answering the telephone",
            "Answering the telephone",
            "Answering the telephone",
            "Answering the telephone",
            "Answering the telephone",
            "Answering the telephone"
    };
}
