package com.beckytech.english1000commonphrases.contents;

public class SubTitleContent {
    public String[] subTitle = {
            "ask direction",
            "give direction",
            "say no in english",
            "say i miss you",
            "hotel",
            "say for example",
            "classroom",
            "say hello",
            "shopping",
            "say good luck",
            "say good job",
            "say I agree",
            "say i am sorry",
            "say good night",
            "say I love you",
            "say because",
            "say i don't know",
            "accept apologies",
            "repeat something",
            "say i am hungry",
            "say good morning",
            "making apologies",
            "accepting apologies",
            "say no",
            "say goodbye",
            "say yes",
            "Birthday",
            "how are you",
            "i don't like it",
            "oh my god",
            "i am tired",
            "say for example in other way",
            "greeting",
            "greeting",
            "greeting",
            "greeting",
            "welcome",
            "surprise",
            "greeted someone",
            "journey or vacation",
            "Small Talk",
            "Small Talk",
            "Small Talk",
            "Small Talk",
            "Small Talk",
            "Small Talk",

            "Introductions",
            "Introductions",
            "Introductions",
            "Introductions",
            "Introductions",

            "Ending a Conversation",
            "Ending a Conversation",
            "Ending a Conversation",

            "Goodbye",
            "Goodbye",
            "Goodbye",
            "Goodbye",
            "Goodbye",

            "agreeing",
            "agreeing",
            "agreeing",
            "agreeing",
            "agreeing",

            "disagreeing",
            "disagreeing",
            "disagreeing",
            "disagreeing",
            "disagreeing",
            "disagreeing",
            "disagreeing",
            "disagreeing",

            "focusing attention",
            "focusing attention",
            "focusing attention",
            "focusing attention",

            "launching the conversation",
            "launching the conversation",
            "launching the conversation",
            "launching the conversation",
            "launching the conversation",
            "launching the conversation",
            "launching the conversation",
            "launching the conversation",
            "launching the conversation",
            "launching the conversation",
            "launching the conversation",

            "making friends",
            "making friends",
            "making friends",
            "making friends",
            "making friends",
            "making friends",
            "making friends",
            "making friends",
            "making friends",

            "complex matters",
            "complex matters",
            "complex matters",
            "complex matters",
            "complex matters",
            "complex matters",
            "complex matters",
            "complex matters",
            "complex matters",
            "complex matters",
            "complex matters",
            "complex matters",
            "complex matters",
            "complex matters",
            "complex matters",
            "complex matters",
            "complex matters",
            "complex matters",
            "complex matters",
            "complex matters",
            "complex matters",
            "complex matters",
            "complex matters",
            "complex matters",
            "complex matters",
            "complex matters",
            "complex matters",
            "complex matters",
            "complex matters",
            "complex matters",
            "complex matters",

            "Disputes",
            "Disputes",
            "Disputes",
            "Disputes",
            "Disputes",
            "Disputes",
            "Disputes",

            "discussion and resolution",
            "discussion and resolution",
            "discussion and resolution",
            "discussion and resolution",
            "discussion and resolution",
            "discussion and resolution",
            "discussion and resolution",
            "discussion and resolution",
            "discussion and resolution",
            "discussion and resolution",
            "discussion and resolution",
            "discussion and resolution",
            "discussion and resolution",
            "discussion and resolution",
            "discussion and resolution",
            "discussion and resolution",
            "discussion and resolution",

            "POLITE ENCOUNTERS - Prefaces",
            "POLITE ENCOUNTERS - Prefaces",
            "POLITE ENCOUNTERS - Prefaces",
            "POLITE ENCOUNTERS - Prefaces",

            "Communication Barriers",
            "Communication Barriers",
            "Communication Barriers",
            "Communication Barriers",

            "Telling Time",
            "Telling Time",
            "Telling Time",
            "Telling Time",
            "Telling Time",
            "Telling Time",
            "Telling Time",
            "Telling Time",
            "Telling Time",
            "Telling Time"
    };
}
