package com.beckytech.english1000commonphrases.contents;

public class TitleContent {
    public String[] title = {
            "Asking Directions in English",
            "Giving Directions in English",
            "Ways to Say NO in English",
            "Ways to Say I MISS YOU",
            "Phrases for Staying at a Hotel",
            "Ways to Say FOR EXAMPLE",
            "English Classroom Phrases",
            "Ways to Say HELLO",
            "Phrases in Shopping",
            "Ways to Say GOOD LUCK",
            "Ways to Say GOOD JOB",
            "Ways to Say I AGREE",
            "Ways to Say I’M SORRY",
            "Ways to Say GOOD NIGHT",
            "Ways to Say I LOVE YOU",
            "Ways to Say BECAUSE",
            "Ways to Say I DON’T KNOW",
            "How to Accept Apologies",
            "How to Ask Someone to Repeat Something",
            "Ways to Say I’M HUNGRY",
            "Ways to Say Good Morning",
            "Making Apologies",
            "Accepting Apologies",
            "Creative Ways to Say NO",
            "Ways to Say GOODBYE",
            "Ways To Say YES",
            "Ways to Say HAPPY BIRTHDAY",
            "Ways to Say HOW ARE YOU?",
            "Ways to Say I DON’T LIKE IT",
            "Ways to Say OH MY GOD!",
            "Ways to Say I’M TIRED",
            "Another Way to Say For Example",
            "Simple greeting",
            "General Greeting",
            "Greetings for various times of the day",
            "Greeting a person you haven’t seen in a long time",
            "Welcoming someone who has returned",
            "Expressing surprise at meeting someone",
            "After you have greeted someone",
            "Concerning a journey or vacation",
            "Expressing your state of health and happiness",
            "Telling how you have been doing—positive",
            "Telling how you have been doing—neutral",
            "Telling how you have been doing—negative",
            "Explaining that you have been busy",
            "Inviting a friend for a drink or coffee",

            "Introducing someone to someone else",
            "When you have just been introduced to someone",
            "After you have been introduced to someone",
            "Asking how someone is",
            "asking someone how things are going",

            "Signaling the end of a conversation",
            "Ending a telephone conversation",
            "Ending a conversation abruptly",

            "Simple good bye",
            "Taking leave of someone",
            "Leaving a place",
            "When someone is leaving on a journey",
            "Making plans to keep in touch with someone",

            "Simple agreement",
            "Stating your concurrence",
            "Expressing acceptance",
            "Stating that you understand",
            "Making sure you are understood",

            "Stating simple disagreement or refusal",
            "Stating categorical disagreement",
            "Stating strong disagreement",
            "Stating your disagreement with a proposition",
            "Expressing rejection",
            "Expressing refusal",
            "Stating that someone is wrong",
            "arguing about the facts",

            "getting someone's attention",
            "getting someone to listen to you",
            "directing attention to an object",
            "confirming that you are paying attention",

            "Stating an informal conversation",
            "Inviting someone to talk",
            "Coming to the point of the matter",
            "Requesting that the speaker get to the point",
            "Various conversational phrases",
            "Encouraging someone to speak plainly",
            "Not digression in a conversation",
            "Repeating what you have said",
            "When someone is being repetitious",
            "Agreeing with a speaker",
            "Answers to \"How did you find out?\"",

            "expressing friendship",
            "Commenting on the uniqueness of someone",
            "commenting on personal similarities",
            "Expressions used to make friends at a bar or cafe",
            "inviting someone to dance",
            "approaching the opposite sex",
            "asking someone for a date",
            "turning someone down",
            "bringing a conversation to an end",

            "Expressing support for someone",
            "Offering help to someone",
            "Expressing trust in someone",
            "Expressing encouragement",
            "Encouraging someone to try something",
            "Encouraging someone to stop stalling and do something",
            "Expressing dissatisfaction with someone's efforts",
            "Asking someone to wait",
            "Encouraging someone to be patient and take things slowly",
            "encouraging someone to be prudent (cliches)",
            "Giving advice to someone whose life is too busy",
            "Giving instructions to someone you've lent something to",
            "Introducing a secret",
            "Instructions about keeping a secret",
            "Promising to keep a secret",
            "Forgetfulness",
            "when you are in trouble",
            "When someone is in trouble",
            "When you are out of money",
            "When someone is in debt",
            "Expressing stress or anxiety",
            "When you are overworked and doing too much",
            "when someone is anxious and under stress",
            "encouraging someone not to be offended (informal)",
            "encouraging someone not to be excited",
            "encouraging someone to relax",
            "Encouraging someone to be less aggressive (informal)",
            "when someone is cold and unfeeling (informal)",
            "what to say to a smoker",
            "a smoker's response to a nonsmoker's complaint",
            "questions a smoker might ask",

            "When someone says something outrageous",
            "Asking in disbelief or disagreement",
            "Encouraging someone to be more sensible",
            "Asking about the alertness of someone",
            "Questioning someone’s sanity",
            "Calling someone crazy",
            "Criticism of someone with whom you disagree",

            "asking for an explanation",
            "Encouraging an explanation",
            "When you do not understand someone",
            "When someone does not understand you",
            "Criticizing someone’s misunderstanding",
            "Attempting to put an end to a misunderstanding",
            "Encouraging someone to believe you",
            "Asking to be trusted",
            "Stating that something is settled",
            "Claiming that something is easy to understand",
            "Showing disbelief",
            "Expressing ignorance",
            "Expressing reluctance",
            "Making the best of a bad situation",
            "Blaming something on fate or destiny",
            "Knowing something after the fact",
            "Expressing indifference",

            "A preface to asking a question",
            "A preface to making a statement—formal",
            "A preface to making a statement—informal",
            "A preface to making a statement—very polite",

            "Asking if someone speaks a particular language",
            "When you do not speak a particular language",
            "When you do not understand what was said",
            "When you do not understand what a foreign visitor has said",

            "Asking the time of day",
            "The time is 12:00 o’clock",
            "The time is on the hour",
            "The time is approximate",
            "The time is ten minutes past the hour",
            "The time is fifteen or thirty minutes past the hour",
            "The time is forty minutes past the hour",
            "The time is forty-five minutes past the hour",
            "The time is fifty minutes past the hour",
            "When a timepiece is not accurate",

            "When your moving about may bother someone",
            "Offering to let someone enter in front of you",
            "Apologizing to someone you have bothered",
            "Returning someone’s good wishes",
            "Agreeing to something—polite",
            "Explaining that you will attend to someone soon",
            "Asking for permission to leave a place—polite",
            "Saying good-bye—polite",
            "Saying good-bye—informal",

            "Announcing your arrival for an appointment",
            "Being assertive polite",

            "Sincere apologies",
            "Offering a very polite apology",
            "Accepting the blame for something",
            "Admitting your errors",
            "Promising never to repeat a particular mistake",
            "Offering to make amends",
            "Asking for forgiveness",

            "Simple forgiving",
            "forgiveness - informal",
            "Encouraging someone to end a dispute",

            "Saying \"thank you\"—formal",
            "Saying \"thank you\"—informal",

            "Acknowledging someone’s thanks—formal",
            "Acknowledging someone’s thanks—informal",

            "Seeing a new baby",
            "Asking about a new baby",
            "Congratulating someone for doing a good job",
            "Wishing someone well",
            "Expressing sympathy at a funeral or wake",

            "When someone is conceited or vain",
            "When someone is overbearing",
            "When someone has been insolent or rude—shocked response",
            "When someone has been insolent or rude—firm response",
            "When someone has been insolent or rude—rude response",
            "Encouraging a timid person",
            "Insulting a coward",
            "When someone argues too much",
            "When someone is being annoying",
            "Inviting an annoying person to leave",
            "When someone is very annoying or hurtful",
            "Getting someone to stop doing something",
            "When someone is making you angry—rude",
            "Asking to be left alone",
            "When someone has done something wrong—polite",
            "When someone has done something wrong—amazed",
            "When someone has done something wrong—sarcastic",
            "When someone makes an unwelcome intervention",
            "Telling someone to stay away or keep out",
            "Asking someone’s intentions",
            "Starting a fight",
            "Asking someone to leave your property alone",
            "Asking someone to stay out of your affairs",
            "When someone is harassing you—angry and direct",
            "When someone is harassing you—rude",
            "When someone is presumptuous",
            "When someone has underestimated your intelligence",
            "When someone interrupts with an opinion",
            "Apologizing—sarcastic",
            "When someone overreacts",
            "When punishment is in store for someone",
            "Explaining harsh justice",
            "Threatening retaliation",
            "Requesting silence",
            "Requesting someone to stop needless talk",
            "When someone is not doing enough",
            "When someone starts trouble",
            "Expressing mock sympathy",
            "Expressing mock sympathy—sarcastic",
            "When you are helpless to help—rude",

            "Asking to visit someone",
            "When you are invited to an informal meal in a home",
            "Asking about an invitation you have received",
            "Apologizing for being late",
            "Explaining why one is late",
            "When you finally arrive after being late",
            "Greetings for visitors",
            "Inviting a visitor to come in",
            "After greeting a visitor",
            "Making a visitor feel welcome and comfortable",
            "Inviting a visitor to stay for dinner",
            "Encouraging a guest to feel at home",
            "Offering a guest a seat",
            "Steering a guest to a particular room",
            "Encouraging a guest to be independent",
            "Mingling with other guests",
            "What a guest says to a host or hostess",
            "Starting a conversation using the topic of weather",
            "Asking a question to start a conversation",
            "Starting a conversation with someone you know well",
            "Starting a conversation in a waiting room",
            "Talking about the weather",
            "What to say when in a crowded place",
            "Preparing to leave home",
            "Stating when you will return home",
            "Preparing to leave a host or hostess",
            "When departing",
            "Questions asked of departing guests",
            "Saying good-bye to departing guests",

            "General exclamations",
            "Religious expressions",
            "Expressions meaning \"almost\"",
            "Leaving things as they are",
            "Expressing differences between people—clichés",
            "Warnings",
            "Giving and receiving - clichés",
            "Cause and effect—clichés",
            "Saying the obvious—clichés",
            "Expressions for a forgotten word or name",
            "Regarding order and procedure",
            "Describing a messy place",
            "Concerning unity—clichés",
            "Concerning nostalgia",
            "Concerning strength—clichés",
            "Concerning rigidity of character—idioms and clichés",
            "Feeling warm or hot",
            "Feeling cool or cold",
            "Describing additional unspecified people or things",
            "Concerning cleanliness",
            "Concerning surprise",
            "Concerning expectation",
            "Concerning a premonition",
            "Concerning being busy—clichés",
            "Making an extra effort",
            "Demanding to be given an object",
            "When someone is preparing for an important event—clichés",
            "When someone is dressed up",
            "When you feel you are not wanted",
            "Regarding something less than what was desired",
            "Describing a reprimand",
            "When something is broken",
            "When something is out of order",
            "On being pushed to the limit of your patience",

            "Beginning a new project or activity",
            "Concerning the deceptively difficult",
            "Concerning the impossible",
            "Concerning futility",
            "When something is unimportant",
            "Ending a project",
            "Starting over again on a project",

            "Asking if someone is all right",
            "Asking why someone looks so unhappy",
            "Offering someone help and advice",
            "Encouraging someone who is unhappy",
            "When you are depressed",
            "Expressing despair and emptiness",
            "When someone looks very happy",
            "When someone is very happy—idioms",
            "Expressing enthusiasm for life",
            "When someone is content",
            "When someone is carefree",
            "When someone is resigned to life as it is",
            "Expressing displeasure with something",
            "Asking someone to stop being unpleasant",
            "Dullness and boredom",
            "Dullness in people",
            "Excitement in people",

            "When you feel out of place",
            "Expressing anger",
            "Expressing fright",
            "When you do not know what to say",

            "Difficulty in hearing",
            "An ear for music",
            "Hearing loud and soft sounds",
            "Concerning ears or hearing",
            "The taste of foods",
            "Offering someone a small portion of food",
            "Expressing hunger",
            "Identifying smells",
            "Physical responses",
            "The sense of touch",
            "Difficulties with seeing",
            "Concerning good vision",
            "Concerning vision and belief",

            "When someone is in good health",
            "Observing that someone looks disorderly",
            "When someone looks very bad",
            "Inquiring about someone’s health or well-being",
            "When someone does not look well",

            "Concerning allergies",
            "Allergic problems with the nose and breathing",
            "When someone sneezes",
            "Allergic problems with the eyes",
            "Allergic problems with the skin",
            "Expressing general feelings of illness",
            "Expressing mild discomfort owing to illness",
            "When you feel like vomiting",
            "Describing a pain in the head",
            "Describing dizziness",
            "Describing being exhausted or worn out",
            "Offering care to a sick person",
            "Concerning catching a disease",
            "Questions for the hospital patient",
            "Explaining that your health is improving",
            "Explaining that you are receiving medical care",
            "Explaining that you are cured of a health problem",

            "Describing family relationships",
            "Family solidarity",
            "Asking about a meal",
            "Announcing a meal",
            "Instructions given to children in the kitchen",
            "Blessing the food",
            "Second servings",
            "Instructing children on good table manners",
            "Doing the dishes",
            "Asking to leave the dinner table early",
            "Instructing children to finish eating",
            "Concerning a radio or stereo",
            "Concerning furniture or carpeting",
            "Concerning television",
            "Changing the television channel",
            "Managing a television set",
            "Concerning computers",
            "Managing a computer",
            "Taking a nap",
            "Going to bed and to sleep",
            "Saying good night",
            "Commands for a dog",
            "Caring for pets"
    };
}
