package com.beckytech.english1000commonphrases.contents;

public class TitleContent {
    public String[] title = {
            "Asking Directions in English",
            "Giving Directions in English",
            "Ways to Say NO in English",
            "Ways to Say I MISS YOU",
            "Phrases for Staying at a Hotel",
            "Ways to Say FOR EXAMPLE",
            "English Classroom Phrases",
            "Ways to Say HELLO",
            "Phrases in Shopping",
            "Ways to Say GOOD LUCK",
            "Ways to Say GOOD JOB",
            "Ways to Say I AGREE",
            "Ways to Say I’M SORRY",
            "Ways to Say GOOD NIGHT",
            "Ways to Say I LOVE YOU",
            "Ways to Say BECAUSE",
            "Ways to Say I DON’T KNOW",
            "English Phrases – How to Accept Apologies",
            "English Phrases – How to Ask Someone to Repeat Something",
            "Ways to Say I’M HUNGRY",
            "Ways to Say Good Morning",
            "Making Apologies",
            "Accepting Apologies",
            "Creative Ways to Say NO",
            "Ways to Say GOODBYE",
            "Ways To Say YES",
            "Ways to Say HAPPY BIRTHDAY",
            "Ways to Say HOW ARE YOU?",
            "Ways to Say I DON’T LIKE IT",
            "Ways to Say OH MY GOD!",
            "Ways to Say I’M TIRED",
            "Another Way to Say For Example",
            "Simple greeting",
            "General Greeting",
            "Greetings for various times of the day",
            "Greeting a person you haven’t seen in a long time",
            "Welcoming someone who has returned",
            "Expressing surprise at meeting someone",
            "After you have greeted someone",
            "Concerning a journey or vacation",
            "Expressing your state of health and happiness",
            "Telling how you have been doing—positive",
            "Telling how you have been doing—neutral",
            "Telling how you have been doing—negative",
            "Explaining that you have been busy",
            "Inviting a friend for a drink or coffee",

            "Introducing someone to someone else",
            "When you have just been introduced to someone",
            "After you have been introduced to someone",
            "Asking how someone is",
            "asking someone how things are going",

            "Signaling the end of a conversation",
            "Ending a telephone conversation",
            "Ending a conversation abruptly",

            "Simple good bye",
            "Taking leave of someone",
            "Leaving a place",
            "When someone is leaving on a journey",
            "Making plans to keep in touch with someone",

            "Simple agreement",
            "Stating your concurrence",
            "Expressing acceptance",
            "Stating that you understand",
            "Making sure you are understood",

            "Stating simple disagreement or refusal",
            "Stating categorical disagreement",
            "Stating strong disagreement",
            "Stating your disagreement with a proposition",
            "Expressing rejection",
            "Expressing refusal",
            "Stating that someone is wrong",
            "arguing about the facts",

            "getting someone's attention",
            "getting someone to listen to you",
            "directing attention to an object",
            "confirming that you are paying attention",

            "Stating an informal conversation",
            "Inviting someone to talk",
            "Coming to the point of the matter",
            "Requesting that the speaker get to the point",
            "Various conversational phrases",
            "Encouraging someone to speak plainly",
            "Not digression in a conversation",
            "Repeating what you have said",
            "When someone is being repetitious",
            "Agreeing with a speaker",
            "Answers to \"How did you find out?\"",

            "expressing friendship",
            "Commenting on the uniqueness of someone",
            "commenting on personal similarities",
            "Expressions used to make friends at a bar or cafe",
            "inviting someone to dance",
            "approaching the opposite sex",
            "asking someone for a date",
            "turning someone down",
            "bringing a conversation to an end",

            "Expressing support for someone",
            "Offering help to someone",
            "Expressing trust in someone",
            "Expressing encouragement",
            "Encouraging someone to try something",
            "Encouraging someone to stop stalling and do something",
            "Expressing dissatisfaction with someone's efforts",
            "Asking someone to wait",
            "Encouraging someone to be patient and take things slowly",
            "encouraging someone to be prudent (cliches)",
            "Giving advice to someone whose life is too busy",
            "Giving instructions to someone you've lent something to",
            "Introducing a secret",
            "Instructions about keeping a secret",
            "Promising to keep a secret",
            "Forgetfulness",
            "when you are in trouble",
            "When someone is in trouble",
            "When you are out of money",
            "When someone is in debt",
            "Expressing stress or anxiety",
            "When you are overworked and doing too much",
            "when someone is anxious and under stress",
            "encouraging someone not to be offended (informal)",
            "encouraging someone not to be excited",
            "encouraging someone to relax",
            "Encouraging someone to be less aggressive (informal)",
            "when someone is cold and unfeeling (informal)",
            "what to say to a smoker",
            "a smoker's response to a nonsmoker's complaint",
            "questions a smoker might ask",
    };
}
