package com.beckytech.english1000commonphrases;

public class ContentDetail {
    public String[] content = {
            "How do I get to library?",
            "Go up…",
            "My body says yes, but my heart say no.",
            "You bring joy to my life.",
            "Do you have a reservation?",
            "For instance",
            "Can you help me, please?",
            "Good to see you",
            "Do you have a smaller size?",
            "You’ll do great.",
            "Much better!",
            "I see what you mean…",
            "I shouldn’t have…",
            "Sleep with angels",
            "I respect you.",
            "now that",
            "That requires a bit more research first.",
            "That's ok!",
            "Excuse me?",
            "I’m hungry as a wolf!",
            "Good morning, sunshine!",
            "I do apologize for…",
            "No need to…",
            "Not possible.",
            "Adios",
            "Why not?",
            "Have a fabulous birthday!",
            "What’s new?",
            "I’m not into it.",
            "Goodness gracious me!",
            "I’m weary",
            "Namely",

            "Where is the nearest post office?\n",
            "Can you tell me the way to the Big Hotel?\n",
            "Are we on the right road for London?\n",
            "Can you Show me on the map, please?\n",
            "I’m looking for this address.\n",
            "How do I find…?\n",
            "Excuse me, How can I go to …?\n",
            "Dou you have a map?\n",
            "Are you from around here?\n",
            "Where is …?\n",
            "Which the best way to …?\n",
            "Pardon me, I’m lost, how do I get to …?\n",
            "I’m looking for …\n",
            "Could you direct me to …?\n",
            "May I ask for some help? I need to get to …?\n",
            "How can we get to High Park?\n",
            "Is it far?\n",
            "Excuse me, could you tell me how to get to the bus station?",

            "It’s on the corner",
            "Go straight ahead",
            "Cross…",
            "Go along…",
            "Turn left",
            "Turn right",
            "Turn left into … Street",
            "It’s in the middle of the block",
            "You will pass a supermarket on your left",
            "Take this road",
            "Turn right at the crossroads",
            "It’s on your left",
            "It’s on your right",
            "It’s about 100 meters from here",
            "Take the first road on the right",
            "Take the second road on the left",
            "It’s next to…",

            "Nope",
            "Maybe another time.",
            "I am not accepting anything else at this time.",
            "We appreciate the offer, but …",
            "I’m not really into it, but thanks for asking!",
            "I’d rather not, thanks.",
            "Nah",
            "That’s not going to work for me.",
            "Sounds fun, but I’m not available.",
            "I want to, but I’m unable to.",
            "I just don’t have that to give right now.",
            "I’m not able to commit to that right now.",
            "It is not a good idea for me.",
            "Apologies, but I can’t make it.",

            "All I do is think of you.",
            "I love being around you.",
            "I’m infatuated with you.",
            "You crossed my mind.",
            "I appreciate you.",
            "I feel sad without you.",
            "You inspire me.",
            "You are my reason for living.",
            "You occupy my thoughts.",
            "I miss your laugh.",
            "I adore you.",
            "You’re everything to me.",
            "You’re the light of my life.",
            "I’m head over heels for you.",
            "I want a lifetime with you.",

            "Do you need help with your bags?",
            "Is there anything else we can help you with?",
            "How many guests are with you?",
            "Your room is on the second floor.",
            "Thank you for staying with us!",
            "I’d like to book a room, please.",
            "We really enjoyed our stay.",
            "The room is too noisy.",
            "Can I see the room, please?",
            "Please sign your name here.",
            "More fresh towels are available at the front desk.",
            "I’d like a single room, please.",
            "Can someone help me with my bags?",
            "When I can check-in?",
            "Do you need a wake-up call?",

            "Additionally",
            "Likewise",
            "Note well",
            "As an example being…",
            "In particular",
            "Let’s say…",
            "This includes",
            "As seen in…",
            "E.g.",
            "One example is…",
            "Such as",
            "In addition to",
            "By way of illustration",
            "In a similar case",
            "Especially",
            "If you look at…",
            "Examples include…",
            "As a case in point…",
            "An example being…",
            "This can be seen when",
            "These include…",
            "As an example",
            "Particularly",
            "Like",

            "Can I go out?",
            "Can I answer the question?",
            "Can I switch off the lights?",
            "Teacher, please can you repeat again?",
            "Can I open the window?",
            "Can we pack our things now?",
            "What page are we on?",
            "I am ready. May I start it?",
            "What is the homework?",
            "Do we have to write this down?",
            "Sorry, for being late.",
            "May I open / close the window?",
            "Can I go to the board?",
            "Can I come in?",
            "Can I pull up the blinds?",
            "Can I spell down the blinds?",
            "May I join the class/group?",
            "Can you explain it once more, please?",
            "May I go out please?",
            "Is this right?",
            "Is this correct?",
            "I am sorry. I did not hear.",
            "Can you speak louder, please?",
            "Which book?",
            "Can you explain that again?",
            "Whe is the exam?",
            "When is the homework for?",
            "I have done this.",
            "Can I go to the toilet?",

            "Hey, boo",
            "Good evening",
            "Good morning",
            "Hello",
            "Hey",
            "How are you feeling today?",
            "Bonjour",
            "Howdy?",
            "How are things?",
            "What have you been up to?",
            "Look what the cat dragged in!",
            "It is nice to meet you",
            "What’s going on?",
            "Good afternoon.",
            "How have you been?",
            "What’s up?",
            "Greeting",
            "Stay safe",
            "Welcome",

            "Where is the changing room?",
            "Do you know where else I could try?",
            "Do you have this item in stock?",
            "Do you offer a cash discount?",
            "Do you have any strawberry?",
            "Do you have a refund policy?",
            "How much is this?",
            "Do you have a bigger size?",
            "Do you sell organic vegetables?",
            "Could you help me please?",
            "Where can I weight my groceries?",
            "Does it come with a guarantee/warranty?",
            "I’m looking for a leather handbag.",
            "Would you have this in another color?",
            "Do you have something less pricey (expensive)?",
            "Where is the fitting room?",

            "Knock them dead!",
            "You are going to be amazing!",
            "Godspeed",
            "Wishing you all the best!",
            "I wish you luck!",
            "Best wishes.",
            "I hope things will turn out fine..",
            "Blow them away!",
            "You’ll do great!",
            "Wishing you lots of luck!",
            "Fingers crossed!",
            "Wishing you a lot of luck!",
            "You were made for this!",
            "I hope things will work out all right.",
            "May the force be with you.",

            "You certainly did well today.",
            "That kind of work makes me happy.",
            "Way to go.",
            "That’s it.",
            "Marvelous!",
            "Cool!",
            "Tremendous!",
            "Fantastic!",
            "Excellent!",
            "Super-Duper!",
            "Out of sight.",
            "Now that’s what I call a fine job.",
            "Couldn’t have done it better myself.",
            "Keep working on it; you’re improving.",
            "It’s such a pleasure to teach when",
            "You work like that!",
            "I think you’re doing the right thing.",
            "Terrific!",

            "So do I.",
            "I fee that way too.",
            "Definitely.",
            "I agree with you.",
            "Yup",
            "Yep",
            "Absolutely!",
            "You’re absolutely right.",
            "Exactly!",
            "We are of one mind.",
            "You can say that again.",
            "I could not agree with you more my friend.",
            "You’ve hit the nail on the head.",
            "You got it dude.",
            "Our thoughts are absolutely parallel.",
            "You are so right.",

            "Excuse me for…",
            "It’s all my fault.",
            "Please, accept my apologies for…",
            "I apologize for…",
            "Please, forgive me for my…",
            "I must apologize for…",
            "Ever so sorry",
            "That’s my fault.",
            "Please don’t be mad at me.",
            "How stupid thoughtless of me.",
            "Please, accept my apologies for…",
            "I’m really ashamed of what I did.",
            "I’m really sorry about what I said.",
            "That was rude of me. I’m sorry.",
            "I hope you’ll forgive me for…",
            "I do apologize for…",

            "Sleep tight, don’t let the bed bugs bite",
            "Let’s start counting the sheep",
            "Tomorrow is not soon enough. Lets prepare.",
            "Time to dream",
            "Night night",
            "Nite-nite",
            "Have a good sleep",
            "Dream of me",
            "Until tomorrow",
            "Rest time for blossoms",
            "Don’t let the bed bugs bite!",
            "I’ll see you in dreamland",
            "Have sea dreams",

            "You are my reason for living.",
            "You are precious.",
            "You complete me.",
            "You’re the love of my life.",
            "I can’t stop thinking about you.",
            "I lost my heart on you.",
            "You inspire me.",
            "I worship you.",
            "You are my everything.",
            "I need you.",
            "I dreamt about you last night.",
            "You bring happiness to rainy days.",
            "I’ve got you under my skin.",
            "You are the reason I’m alive.",
            "You are my dear.",
            "I’m affectionate for you.",
            "I’m wild about you.",
            "You’re all I see.",
            "I want you.",
            "You are my reason for living.",
            "I lost my heart on you.",
            "You complete me.",

            "on the grounds that",
            "over",
            "owing to",
            "seeing",
            "as things go",
            "being",
            "by cause of",
            "by reason of",
            "by virtue of",
            "considering",
            "since",
            "thanks to",
            "through",
            "whereas",
            "for the reason that",
            "for the sake of",
            "in as much as",
            "in behalf of",
            "in that",
            "in the interest of",

            "Beats me.",
            "I don’t know anything about …",
            "I’m going to investigate that further.",
            "It’s beyond me.",
            "It’s a mystery to me.",
            "That’s a good question, but I don’t know.",
            "I’m not the best person to answer that.",
            "That’s a good question, I’II check this.",
            "I’m afraid. I’ve no idea.",
            "I can’t remember off the top of my head.",
            "I don’t have any information about that.",
            "That’s exactly what I’m seeking to answer.",
            "Who knows?",
            "Let me check on that.",
            "I’m not 100% sure on that.",
            "I’ll double check and let you know.",

            "I quite understand.",
            "You couldn’t help it.",
            "Forget about it.",
            "Don’t worry about it.",
            "That’s all right.",
            "It doesn’t matter.",
            "Don’t worry. You’re forgiven!",
            "It’s ok.",
            "No need to…",
            "No harm done.",
            "Don’t apologize.",
            "Never mind.",
            "There’s no need to. It’s all right.",
            "Never mind. I quite understand.",
            "Forget about it. I understand.",
            "There is no need. It’s ok.",

            "Do you mind repeating that?",
            "Sorry, I didn’t hear what you said.",
            "Sorry, I didn’t catch that.",
            "Could you pleasse repeat that?",
            "Would you mind repeating that?",
            "Pardon?",
            "Sorry",
            "I’m sorry, I don’t understand. Could you repeat that, please?",
            "Let me repeat that just to make sure?",

            "I’m hungry as a bear!",
            "Famishing",
            "Flying light",
            "Got the munchies",
            "Hankering",
            "My tummy is talking to me.",
            "I’m freaking hungry!",
            "Eager",
            "Greedy",
            "Keen",
            "Ravenous",
            "Starved",
            "Famished",
            "Hoggish",
            "Hollow",
            "I’m so hungry I could eat a scabby horse.",

            "Mornin’ mi Amigo! (Male)",
            "Mornin’ mi Amiga! (Female)",
            "Morning, good looking!",
            "Rise and shine!",
            "Morning!",
            "Wakey-wakey!",
            "Good day to you!",
            "Good morning, Sleeping beauty!",

            "I must apologize for…",
            "Please, accept my apologies for…",
            "I apologize for…",
            "Please, forgive me for my…",
            "I’d like to apologize for…",
            "Pardon me for this…",
            "I am so sorry for…",
            "I’m terribly sorry for…",
            "I shouldn’t have…",
            "Excuse me for…",
            "It’s all my fault.",
            "Please, forgive me for…",
            "I’m ashamed of…",
            "I’m really ashamed of what I did.",
            "I’m really sorry about what I said.",
            "That was rude of me. I’m sorry.",
            "I hope you’ll forgive me for…",

            "No harm done.",
            "Don’t apologize.",
            "Never mind.",
            "It’s ok.",
            "Don’t mention it.",
            "That’s OK.",
            "I quite understand.",
            "You couldn’t help it.",
            "Forget about it.",
            "Don’t worry about it.",
            "That’s all right.",
            "It doesn’t matter.",
            "Don’t worry. You’re forgiven!",
            "There’s no need to. It’s all right.",
            "Never mind. I quite understand.",
            "Forget about it. I understand.",
            "There is no need. It’s ok.",

            "By no means.",
            "I’m slammed.",
            "Not for me, thanks.",
            "Unfortunately, that’s not something I can do at this time.",
            "I’m really booked.",
            "Thanks for thinking of me. I really wish I could.",
            "That’s not an option.",
            "This is not negotiable.",
            "I think not.",
            "If only it worked, but …",
            "Not for me my friend, thanks.",
            "I have something else.",
            "I’d like to, but I know I’II regret it.",
            "I really appreciate you asking me, bu t I can’t do it.",
            "I really appreciate you asking me but I can’t commit to that right now.",
            "No, thanks.",
            "Thanks for thinking of me but I can’t",
            "Unfortunately not.",
            "I’m afraid I can’t.",
            "Maybe another time.",
            "I’m sorry I’m busy.",
            "That’s not going to work for me.",
            "Maybe next time.",
            "I’d love to – but can’t.",
            "My body say yes, but my heart say no.",
            "That doesn’t work for me.",
            "I wish I could make it work.",
            "I am honoured that you asked me but I can’t do it.",
            "Sounds tempting, but I’II have to pass.",

            "Bye now",
            "Bye-bye",
            "Take it easy",
            "Aloha",
            "Cheerio",
            "I’m off",
            "Gotta go!",
            "Good night",
            "I gotta take off",
            "Talk to you later",
            "Keep in touch",
            "Lovely to meet you",
            "Peace!",
            "See ya!",
            "Catch you later",
            "Have a good one",
            "Be seeing you!",

            "Brilliant!",
            "Uh-huh",
            "Willingly",
            "Sure I can!",
            "Cool!",
            "No problem",
            "Yes, what is it?",
            "Exactly!",
            "Absolutely",
            "You bet",
            "Good!",
            "Undoubtedly!",
            "I shall!",
            "Si!",
            "As you wish!",
            "Permission granted!",
            "Yes, what can I do for you?",
            "Precisely!",

            "I hope you have a fantastic day.",
            "Have a great one!",
            "Wishing you many more candles to blow.",
            "Many happy returns of the day!",
            "All the best on your special day!",
            "Many happy returns!",
            "I wish you a wonderful birthday!",
            "Have a good one!",
            "May you birthday be filled with laughter!",
            "I wish you all the best on your special day.",
            "I hope you have a fantastic day and a fantastic year to come.",
            "I wish you a wonderful day!",
            "Wishing you a day that is as special as you are!",
            "Congratulations on another year of skillful death evasion!",
            "Hope you have an enjoyable birthday! You deserve it.",

            "How’s it going?",
            "How’s everything?",
            "How’s life?",
            "What’s going on?",
            "What’s happening?",
            "How do you do?",
            "What are you up to?",
            "How are you doing?",
            "How are you holding up?",
            "Whassup?",
            "How are things going?",
            "How are you been?",

            "I can’t stand it.",
            "I hate it.",
            "I’m not a big fan of it.",
            "I’ve had enough.",
            "I’m not crazy about it.",
            "I loathe it.",
            "I am sick of it.",
            "I don’t appreciate it.",
            "I’m not really fond of it.",
            "I’II pass.",
            "I am not passionate about it.",
            "I am not keen on it.",
            "That’s not for me.",
            "I am not a big fan of it.",
            "That’s not my thing.",
            "I’m disinterested in that.",

            "Oh my!",
            "Holy moly",
            "For heaven’s sake!",
            "Oh Jesus!",
            "Blimey!",
            "For the love of God!",
            "Gosh almighty!",
            "Shitting Hell!",
            "That is bare sick!",
            "Heavens to Betsy!",
            "Holy crap",
            "Oh my goodness!",
            "Oh boy!",

            "I’m bushed",
            "I’m beat",
            "I’m done",
            "I’m sleepy",
            "I’m spent",
            "I’m flat out tired",
            "I’m dead-tired",
            "I’m running on fumes",
            "I’m dog tired",
            "I’m tired to the bone",
            "I’m knockered",
            "I’m pooped",
            "I’m exhausted",
            "I’m worn out",
            "I’m dead on my feet",
            "I’m dragging",
            "I’m running on empty",

            "To illustrate",
            "For instance",
            "Additionally",
            "like",
            "One example is…",
            "As a case in point",
            "As an example",
            "Such as",
            "Especially",
            "In a similar case",
            "Also",
            "In addition to",
            "By way of illustration",
            "Likewise",
            "Note well",
            "As an example being…",
            "In particular",
            "Let’s say…",
            "As seen in…",
            "This is illustrated…",
            "These include…",
            "Particularly",
            "Note well…"
    };
}
